import dotenv from 'dotenv';
dotenv.config();

interface Config {
    PROBLEM_SERVICE_DATABASE_URL : string
    REDIS_URL : string;
    SERVICE_NAME : string;
    GRPC_PROBLEM_SERVICE_SERVER_URL : string;
    PROBLEM_SERVICE_METRICS_PORT : number;
    PROBLEM_DETAILS_CACHE_EXPIRY : number;
    DEFAULT_GRPC_TIMEOUT: number;
    GRPC_AUTH_USER_SERVICE_URL : string;
}

export const config : Config = {
    PROBLEM_SERVICE_DATABASE_URL : process.env.PROBLEM_SERVICE_DATABASE_URL!,
    REDIS_URL : process.env.REDIS_URL!,
    GRPC_PROBLEM_SERVICE_SERVER_URL : process.env.GRPC_PROBLEM_SERVICE_SERVER_URL!,
    PROBLEM_SERVICE_METRICS_PORT : Number(process.env.PROBLEM_SERVICE_METRICS_PORT)!,
    SERVICE_NAME : "PROBLEM_SERVICE",
    PROBLEM_DETAILS_CACHE_EXPIRY : Number(process.env.PROBLEM_DETAILS_CACHE_EXPIRY)!,
    DEFAULT_GRPC_TIMEOUT : Number(process.env.DEFAULT_GRPC_TIMEOUT)!,
    GRPC_AUTH_USER_SERVICE_URL : process.env.GRPC_AUTH_USER_SERVICE_URL!
}